#!/usr/bin/env python3
"""
Verify Python file size constraints for Claude Code.

This hook runs after file modifications to check that Python files
in the backend don't exceed 500 lines. Files exceeding this limit
are reported and work items are created in Plane for refactoring.
"""
import json
import sys
from pathlib import Path
from typing import List, Tuple, Optional, Dict
from urllib.error import URLError, HTTPError
from urllib.request import Request, urlopen

from prp_settings import load_settings, get_plane_config, get_project_root


# Configuration
MAX_LINES = 500
REPORT_FILE = ".claude/hooks/oversized_files_report.txt"
TRACKED_ISSUES_FILE = ".claude/hooks/tracked_oversized_issues.json"

# Directories and files to exclude from checking
EXCLUDED_DIRS = {
    "__pycache__",
    ".git",
    "migrations",
    "node_modules",
    "venv",
    ".venv",
    "env",
    ".env",
    "dist",
    "build",
    ".pytest_cache",
    ".mypy_cache",
    "site-packages",
}

EXCLUDED_FILES = {
    "__init__.py",  # Often just imports
}


def load_tracked_issues(project_root: Path) -> Dict[str, str]:
    """Load tracked issues from JSON file."""
    tracked_file = project_root / TRACKED_ISSUES_FILE
    if tracked_file.exists():
        try:
            with open(tracked_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return {}


def save_tracked_issues(project_root: Path, tracked: Dict[str, str]) -> None:
    """Save tracked issues to JSON file."""
    tracked_file = project_root / TRACKED_ISSUES_FILE
    tracked_file.parent.mkdir(parents=True, exist_ok=True)
    with open(tracked_file, "w", encoding="utf-8") as f:
        json.dump(tracked, f, indent=2)


def count_lines(file_path: Path) -> int:
    """Count lines in a Python file."""
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            lines = f.readlines()
        return len(lines)
    except Exception:
        return 0


def should_check_file(file_path: Path) -> bool:
    """Determine if a file should be checked."""
    for part in file_path.parts:
        if part in EXCLUDED_DIRS:
            return False
    if file_path.name in EXCLUDED_FILES:
        return False
    if file_path.suffix != ".py":
        return False
    return True


def find_oversized_files(backend_path: Path) -> List[Tuple[Path, int]]:
    """Find all Python files exceeding the line limit."""
    oversized = []
    if not backend_path.exists():
        return oversized

    for py_file in backend_path.rglob("*.py"):
        if not should_check_file(py_file):
            continue
        line_count = count_lines(py_file)
        if line_count > MAX_LINES:
            oversized.append((py_file, line_count))

    oversized.sort(key=lambda x: x[1], reverse=True)
    return oversized


def create_plane_issue(
    config: Dict[str, str],
    file_path: str,
    line_count: int,
    excess: int,
    project_id: str,
    state_id: str,
) -> Optional[str]:
    """Create a Plane issue for an oversized file."""
    url = f"{config['api_url']}/workspaces/{config['workspace_slug']}/projects/{project_id}/issues/"

    issue_data = {
        "name": f"Refactor: {file_path} ({line_count} lines)",
        "description_html": f"""<p>This file exceeds the 500-line limit and needs refactoring.</p>
<h3>File Details</h3>
<ul>
<li><strong>Path:</strong> {file_path}</li>
<li><strong>Current lines:</strong> {line_count}</li>
<li><strong>Over limit by:</strong> {excess} lines</li>
</ul>
<h3>Refactoring Guidelines</h3>
<ol>
<li>Split into smaller, focused modules</li>
<li>Extract helper functions to utility files</li>
<li>Move related functionality to separate domain modules</li>
<li>Consider creating service classes for complex logic</li>
</ol>
<p><em>Auto-generated by verify_file_size hook</em></p>""",
        "state": state_id,
        "priority": "medium" if line_count < 1000 else "high",
    }

    data = json.dumps(issue_data).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        "X-API-Key": config["api_key"],
    }

    req = Request(url, data=data, headers=headers, method="POST")

    try:
        with urlopen(req, timeout=10) as resp:
            response_data = json.loads(resp.read().decode("utf-8"))
            return response_data.get("id")
    except HTTPError as exc:
        error_body = exc.read().decode("utf-8", "ignore")
        print(f"Plane API error {exc.code}: {error_body}", file=sys.stderr)
    except URLError as exc:
        print(f"Plane connection error: {exc.reason}", file=sys.stderr)
    except Exception as exc:
        print(f"Error creating Plane issue: {exc}", file=sys.stderr)

    return None


def generate_report(oversized_files: List[Tuple[Path, int]], project_root: Path) -> str:
    """Generate a report of oversized files."""
    if not oversized_files:
        return ""

    lines = [
        "=" * 60,
        "OVERSIZED FILES REPORT - Files exceeding 500 lines",
        "=" * 60,
        "",
        f"Found {len(oversized_files)} file(s) that need refactoring:",
        "",
    ]

    for file_path, line_count in oversized_files:
        try:
            rel_path = file_path.relative_to(project_root)
        except ValueError:
            rel_path = file_path
        excess = line_count - MAX_LINES
        lines.append(f"  {rel_path}")
        lines.append(f"    Lines: {line_count} (+{excess} over limit)")
        lines.append("")

    lines.extend([
        "-" * 60,
        "RECOMMENDED ACTIONS:",
        "  1. Split large files into smaller, focused modules",
        "  2. Extract helper functions to utility files",
        "  3. Move related functionality to separate domain modules",
        "  4. Consider creating service classes for complex logic",
        "-" * 60,
    ])

    return "\n".join(lines)


def save_report(report: str, project_root: Path) -> Path:
    """Save the report to a file."""
    report_path = project_root / REPORT_FILE
    report_path.parent.mkdir(parents=True, exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)
    return report_path


def verify_file_sizes() -> bool:
    """
    Check file size constraints in the backend.
    Creates Plane issues for files exceeding the limit.

    Returns:
        True if all files are within limits, False if some exceed.
    """
    project_root = get_project_root()
    settings = load_settings(project_root)
    backend_dir = settings["project"]["backend_dir"]
    backend_path = project_root / backend_dir

    if not backend_path.exists():
        return True

    oversized_files = find_oversized_files(backend_path)

    if not oversized_files:
        # All files within limit - clean up old report if exists
        report_path = project_root / REPORT_FILE
        if report_path.exists():
            report_path.unlink()
        return True

    # Generate and save report
    report = generate_report(oversized_files, project_root)
    report_path = save_report(report, project_root)

    # Output to stderr so it's visible
    print(report, file=sys.stderr)
    print(f"\nReport saved to: {report_path}", file=sys.stderr)

    # Create Plane issues for new oversized files
    plane_config = get_plane_config(settings)
    state_id = settings["plane"].get("backlog_state_id", "")

    if plane_config and state_id:
        project_id = plane_config["project_id"]
        tracked_issues = load_tracked_issues(project_root)
        new_issues_created = 0

        for file_path, line_count in oversized_files:
            try:
                rel_path = str(file_path.relative_to(project_root))
            except ValueError:
                rel_path = str(file_path)

            # Skip if we already created an issue for this file
            if rel_path in tracked_issues:
                continue

            excess = line_count - MAX_LINES
            issue_id = create_plane_issue(
                plane_config, rel_path, line_count, excess, project_id, state_id
            )

            if issue_id:
                tracked_issues[rel_path] = issue_id
                new_issues_created += 1
                print(f"Created Plane issue for: {rel_path}", file=sys.stderr)

        if new_issues_created > 0:
            save_tracked_issues(project_root, tracked_issues)
            print(f"\nCreated {new_issues_created} new Plane issue(s)", file=sys.stderr)
    else:
        if not plane_config:
            print("\nPlane API not configured - skipping issue creation", file=sys.stderr)
        else:
            print("\nPlane backlog_state_id not set - skipping issue creation", file=sys.stderr)

    return False


if __name__ == "__main__":
    within_limits = verify_file_sizes()

    if within_limits:
        print("All backend Python files are within the 500-line limit.", file=sys.stderr)

    # Always exit successfully to not block Claude
    sys.exit(0)
